language: python
python:
    - '2.7'
services: mongodb
install: pip install -r requirements.txt
script: python setup.py test
deploy:
    provider: pypi
    user: CharlesThomas
    password:
        secure: bGQCB610lnUAfqen2YdAphxdGfDJi9qLA3+qPQ7ko13X25iviJbBiGBCW/2R8yOMwEBw/v7a9bYWWfD5+QtUpzzoWzzVMsOqgptYFpVZiF9XPA3/DCG5TqVzTNBFQX25FDcEfZFUPVzGZcuQst5qYgHROAJzyiHxkBwYOJn6lvU=
    on:
        tags: true
